---
# Fetch data from DAQ nodes

- name: fetch data
  hosts: active
  remote_user: attpc
  
  vars:
    - remote_path: /data/attpcX
    - local_path_root: /data/fetched
  
  tasks:
    - name: Sync data folders
      synchronize: mode=pull src="{{ remote_path }}" 
        dest="{{ local_path_root }}/{{ inventory_hostname }}"
        copy_links=yes
