---
# Distribute root's ssh public key to the daq nodes. This is used for maintenance.

- name: distribute attpc public key
  hosts: macminis
  remote_user: attpc
  
  tasks:
    - name: authorize attpc public key
      authorized_key: user=attpc manage_dir=yes key="{{ lookup('file', '/Users/attpc/.ssh/id_rsa.pub') }}"
        state=present
