---
# Distribute attpc's ssh public key to the daq nodes.

- name: distribute attpc public key
  hosts: macminis
  remote_user: attpc
  
  tasks:
    - name: authorize attpc public key
      authorized_key: user=attpc manage_dir=yes key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state=present
