---
# This contains tasks to install dependencies for the DAQ server software

- name: install dependencies for daq
  yum: name={{ item }} state=present
  with_items:
    - gsoap
    - gsoap-devel
    - log4cxx
    - log4cxx-devel
    - xerces-c
    - xerces-c-devel
    - tcsh
    - nedit
    - xterm
    - libtool
    - monotone
    - autoconf
    - uuid-devel
    - subversion
    - expat
    - expat-devel
    - perl-CPAN
    - log4j
    
- name: install dependencies for GET
  yum: name={{ item }} state=present
  with_items:
    - qwt
    - qwt-devel
    - boost-devel
    - ice
    - ice-devel

- name: install other convenient packages
  yum: name={{ item }} state=present
  with_items: 
    - vim
    - telnet

# The next one is required for the perl packages

- name: install cpanminus
  yum: name=perl-App-cpanminus state=present

- name: install perl packages
  cpanm: name={{ item }} 
  with_items:
    - Fatal
    - XML::Parser
    - XML::Parser::Wrapper
    - XML::SAX
