---
# Install the Ganil DAQ packages

- name: create the daq folder
  file: path=/daq owner=attpc group=attpc state=directory
  sudo: yes

- name: sync packages
  synchronize: src=/daq/packages dest=/daq

- name: sync ACQ_HOST links
  synchronize: src=/daq/ACQ_HOST dest=/daq
